name: tennis
ext: '.jpg'
root_dir: /root/repos/tennis-lab/data/tennis
csv_filename: 'Label.csv'
visible_flags: [1,2]

visibility:
  mode: "none" # any_visible, all_visible, none
sequence:
  output_temporal: true
train:
  matches: [ 'game1', 
             'game2', 
             'game3', 
             'game4', 
             'game5', 
             'game6',
             'game7',
             'game11',
             'game12',
             'game13',
             'game14']
  num_clip_ratio: 1.0
  refine_npz_path: 
test:
  matches: [ 'game8', 
             'game9', 
             'game10']
  num_clip_ratio: 1.0
  refine_npz_path:

